spring.application.name=crawlernode
server.port=8090

# 节点名称
node.id=node-1
firecrawl.api-key=fc-b6bc0689abf1457d949fb291932ad914
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# 设置 RabbitTemplate 默认使用的交换机
spring.rabbitmq.template.exchange=crawler.exchange